# Generated by Django 4.1.7 on 2023-03-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_category_auction_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='bids',
        ),
        migrations.AddField(
            model_name='bid',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='auctions.category'),
        ),
    ]
