# Generated by Django 4.1.7 on 2023-03-28 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid_user_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_list',
            name='last_bidder',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='auction_bid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bid',
            name='URL',
            field=models.URLField(blank=True),
        ),
    ]
