# Generated by Django 4.1.7 on 2023-03-29 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_list_last_bidder_alter_bid_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='categories',
        ),
        migrations.AddField(
            model_name='bid',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='auction_list',
            name='last_bidder',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='auction_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
