# Generated by Django 4.1.7 on 2023-03-29 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_bid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_list',
            name='bid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='auction_bid', to='auctions.bid'),
        ),
    ]
