# Generated by Django 4.1.7 on 2023-03-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auction_list_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_list',
            name='number_bids',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
