# Generated by Django 4.1.7 on 2023-03-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auction_list_number_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_list',
            name='state_bid',
            field=models.BooleanField(default=True),
        ),
    ]
