# Generated by Django 4.1.7 on 2023-04-02 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='bid',
        ),
        migrations.AddField(
            model_name='comment',
            name='auction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comment_bid', to='auctions.auction_list'),
        ),
    ]
